INSERT INTO "city" VALUES (1, 'Karachi');
INSERT INTO "city" VALUES (2, 'Lahore');
INSERT INTO "city" VALUES (3, 'Faisalabad');
INSERT INTO "city" VALUES (4, 'Rawalpindi');
INSERT INTO "city" VALUES (5, 'Multan');
INSERT INTO "city" VALUES (6, 'Hyderabad');
INSERT INTO "city" VALUES (7, 'Gujranwala');
INSERT INTO "city" VALUES (8, 'Peshawar');
INSERT INTO "city" VALUES (9, 'Islamabad');
INSERT INTO "city" VALUES (10, 'Bahawalpur');
INSERT INTO "city" VALUES (11, 'Sargodha');
INSERT INTO "city" VALUES (12, 'Sialkot');
INSERT INTO "city" VALUES (13, 'Quetta');
INSERT INTO "city" VALUES (14, 'Sukkur');
INSERT INTO "city" VALUES (15, 'Jhang');
INSERT INTO "city" VALUES (16, 'Shekhupura');
INSERT INTO "city" VALUES (17, 'Mardan');
INSERT INTO "city" VALUES (18, 'Gujrat');
INSERT INTO "city" VALUES (19, 'Larkana');
INSERT INTO "city" VALUES (20, 'Kasur');
INSERT INTO "city" VALUES (21, 'Rahim Yar Khan');
INSERT INTO "city" VALUES (22, 'Sahiwal');
INSERT INTO "city" VALUES (23, 'Okara');
INSERT INTO "city" VALUES (24, 'Wah Cantonment');
INSERT INTO "city" VALUES (25, 'Dera Ghazi Khan');
INSERT INTO "city" VALUES (26, 'Mingora');
INSERT INTO "city" VALUES (27, 'Mirpur Khas');
INSERT INTO "city" VALUES (28, 'Chiniot');
INSERT INTO "city" VALUES (29, 'Nawabshah');
INSERT INTO "city" VALUES (30, 'Kamoke');
INSERT INTO "city" VALUES (31, 'Burewala');
INSERT INTO "city" VALUES (32, 'Jhelum');
INSERT INTO "city" VALUES (33, 'Sadiqabad');
INSERT INTO "city" VALUES (34, 'Khanewal');
INSERT INTO "city" VALUES (35, 'Hafizabad');
INSERT INTO "city" VALUES (36, 'Kohat');
INSERT INTO "city" VALUES (37, 'Jacobabad');
INSERT INTO "city" VALUES (38, 'Shikarpur');
INSERT INTO "city" VALUES (39, 'Muzaffargarh');
INSERT INTO "city" VALUES (40, 'Khanpur');
INSERT INTO "city" VALUES (41, 'Gojra');
INSERT INTO "city" VALUES (42, 'Bahawalnagar');
INSERT INTO "city" VALUES (43, 'Abbottabad');
INSERT INTO "city" VALUES (44, 'Muridke');
INSERT INTO "city" VALUES (45, 'Pakpattan');
INSERT INTO "city" VALUES (46, 'Khuzdar');
INSERT INTO "city" VALUES (47, 'Jaranwala');
INSERT INTO "city" VALUES (48, 'Chishtian');
INSERT INTO "city" VALUES (49, 'Daska');
INSERT INTO "city" VALUES (50, 'Bhalwal');
INSERT INTO "city" VALUES (51, 'Mandi Bahauddin');
INSERT INTO "city" VALUES (52, 'Ahmadpur East');
INSERT INTO "city" VALUES (53, 'Kamalia');
INSERT INTO "city" VALUES (54, 'Tando Adam');
INSERT INTO "city" VALUES (55, 'Khairpur');
INSERT INTO "city" VALUES (56, 'Dera Ismail Khan');
INSERT INTO "city" VALUES (57, 'Vehari');
INSERT INTO "city" VALUES (58, 'Nowshera');
INSERT INTO "city" VALUES (59, 'Dadu');
INSERT INTO "city" VALUES (60, 'Wazirabad');
INSERT INTO "city" VALUES (61, 'Khushab');
INSERT INTO "city" VALUES (62, 'Charsada');
INSERT INTO "city" VALUES (63, 'Swabi');
INSERT INTO "city" VALUES (64, 'Chakwal');
INSERT INTO "city" VALUES (65, 'Mianwali');
INSERT INTO "city" VALUES (66, 'Tando Allahyar');
INSERT INTO "city" VALUES (67, 'Kot Adu');
INSERT INTO "city" VALUES (68, 'Turbat');
